/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Praktikum9;
// Referensi, coba baca dibawah ini ,,,,
// http://uniqosmart.blogspot.com/2015/03/gui-java-desktop-program-kalkulator.html

/**
 *
 * @author User
 */
public class Percobaan2 extends javax.swing.JFrame {
    String bilangan="";
    double hasil,bilangan1,bilangan2;
    int pilih;
    /**
     * Creates new form Percobaan3
     */
    public Percobaan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kolom = new javax.swing.JTextField();
        t1 = new javax.swing.JButton();
        t2 = new javax.swing.JButton();
        t3 = new javax.swing.JButton();
        t4 = new javax.swing.JButton();
        t5 = new javax.swing.JButton();
        t6 = new javax.swing.JButton();
        t7 = new javax.swing.JButton();
        t8 = new javax.swing.JButton();
        t9 = new javax.swing.JButton();
        t0 = new javax.swing.JButton();
        tplus = new javax.swing.JButton();
        tmin = new javax.swing.JButton();
        tkali = new javax.swing.JButton();
        tbagi = new javax.swing.JButton();
        tc = new javax.swing.JButton();
        thasil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setPreferredSize(new java.awt.Dimension(270, 325));
        setResizable(false);
        setSize(new java.awt.Dimension(250, 300));
        getContentPane().setLayout(null);

        kolom.setBackground(new java.awt.Color(153, 255, 255));
        kolom.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        kolom.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        kolom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomActionPerformed(evt);
            }
        });
        getContentPane().add(kolom);
        kolom.setBounds(10, 20, 230, 40);

        t1.setBackground(new java.awt.Color(0, 153, 255));
        t1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setText("1");
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t1MouseClicked(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(10, 80, 50, 40);

        t2.setBackground(new java.awt.Color(0, 153, 255));
        t2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 255, 255));
        t2.setText("2");
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(70, 80, 50, 40);

        t3.setBackground(new java.awt.Color(0, 153, 255));
        t3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        t3.setForeground(new java.awt.Color(255, 255, 255));
        t3.setText("3");
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(130, 80, 50, 40);

        t4.setBackground(new java.awt.Color(0, 153, 255));
        t4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        t4.setForeground(new java.awt.Color(255, 255, 255));
        t4.setText("4");
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        getContentPane().add(t4);
        t4.setBounds(10, 130, 50, 40);

        t5.setBackground(new java.awt.Color(0, 153, 255));
        t5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        t5.setForeground(new java.awt.Color(255, 255, 255));
        t5.setText("5");
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(70, 130, 50, 40);

        t6.setBackground(new java.awt.Color(0, 153, 255));
        t6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        t6.setForeground(new java.awt.Color(255, 255, 255));
        t6.setText("6");
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        getContentPane().add(t6);
        t6.setBounds(130, 130, 50, 40);

        t7.setBackground(new java.awt.Color(0, 153, 255));
        t7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        t7.setForeground(new java.awt.Color(255, 255, 255));
        t7.setText("7");
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        getContentPane().add(t7);
        t7.setBounds(10, 180, 50, 40);

        t8.setBackground(new java.awt.Color(0, 153, 255));
        t8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        t8.setForeground(new java.awt.Color(255, 255, 255));
        t8.setText("8");
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        getContentPane().add(t8);
        t8.setBounds(70, 180, 50, 40);

        t9.setBackground(new java.awt.Color(0, 153, 255));
        t9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        t9.setForeground(new java.awt.Color(255, 255, 255));
        t9.setText("9");
        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });
        getContentPane().add(t9);
        t9.setBounds(130, 180, 50, 40);

        t0.setBackground(new java.awt.Color(0, 153, 255));
        t0.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        t0.setForeground(new java.awt.Color(255, 255, 255));
        t0.setText("0");
        t0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t0ActionPerformed(evt);
            }
        });
        getContentPane().add(t0);
        t0.setBounds(10, 230, 50, 40);

        tplus.setBackground(new java.awt.Color(51, 51, 255));
        tplus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tplus.setForeground(new java.awt.Color(255, 255, 255));
        tplus.setText("+");
        tplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tplusActionPerformed(evt);
            }
        });
        getContentPane().add(tplus);
        tplus.setBounds(190, 80, 50, 40);

        tmin.setBackground(new java.awt.Color(51, 51, 255));
        tmin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tmin.setForeground(new java.awt.Color(255, 255, 255));
        tmin.setText("-");
        tmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tminActionPerformed(evt);
            }
        });
        getContentPane().add(tmin);
        tmin.setBounds(190, 130, 50, 40);

        tkali.setBackground(new java.awt.Color(51, 51, 255));
        tkali.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tkali.setForeground(new java.awt.Color(255, 255, 255));
        tkali.setText("*");
        tkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkaliActionPerformed(evt);
            }
        });
        getContentPane().add(tkali);
        tkali.setBounds(190, 180, 50, 40);

        tbagi.setBackground(new java.awt.Color(51, 51, 255));
        tbagi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tbagi.setForeground(new java.awt.Color(255, 255, 255));
        tbagi.setText("/");
        tbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbagiActionPerformed(evt);
            }
        });
        getContentPane().add(tbagi);
        tbagi.setBounds(190, 230, 50, 40);

        tc.setBackground(new java.awt.Color(153, 255, 255));
        tc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tc.setForeground(new java.awt.Color(0, 0, 0));
        tc.setText("C");
        tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcActionPerformed(evt);
            }
        });
        getContentPane().add(tc);
        tc.setBounds(70, 230, 50, 40);

        thasil.setBackground(new java.awt.Color(0, 102, 204));
        thasil.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        thasil.setForeground(new java.awt.Color(255, 255, 255));
        thasil.setText("=");
        thasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thasilActionPerformed(evt);
            }
        });
        getContentPane().add(thasil);
        thasil.setBounds(130, 230, 50, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tplusActionPerformed
        // TODO add your handling code here:
        bilangan1=Double.parseDouble(bilangan);
        kolom.setText("+");
        bilangan+="";
        pilih=1;
    }//GEN-LAST:event_tplusActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
        bilangan+="1";
        kolom.setText(bilangan);
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
        bilangan+="2";
        kolom.setText(bilangan);    
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
        bilangan+="3";
        kolom.setText(bilangan);     
    }//GEN-LAST:event_t3ActionPerformed

    private void kolomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_kolomActionPerformed

    private void tminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tminActionPerformed
        // TODO add your handling code here:
        bilangan1=Double.parseDouble(bilangan);
        bilangan="";
        kolom.setText("-");
        pilih=2;
    }//GEN-LAST:event_tminActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
        bilangan+="4";
        kolom.setText(bilangan);
    }//GEN-LAST:event_t4ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
        bilangan+="5";
        kolom.setText(bilangan);
    }//GEN-LAST:event_t5ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
        bilangan+="6";
        kolom.setText(bilangan);
    }//GEN-LAST:event_t6ActionPerformed

    private void tkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkaliActionPerformed
        // TODO add your handling code here:
        bilangan1=Double.parseDouble(bilangan);
        bilangan="";
        kolom.setText("*");
        pilih=3;
    }//GEN-LAST:event_tkaliActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
        bilangan+="7";
        kolom.setText(bilangan);
    }//GEN-LAST:event_t7ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
        bilangan+="8";
        kolom.setText(bilangan);
    }//GEN-LAST:event_t8ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
        bilangan+="9";
        kolom.setText(bilangan);
    }//GEN-LAST:event_t9ActionPerformed

    private void tbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbagiActionPerformed
        // TODO add your handling code here:
        bilangan1=Double.parseDouble(bilangan);
        bilangan="";
        kolom.setText("/");
        pilih=4;
    }//GEN-LAST:event_tbagiActionPerformed

    private void t0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t0ActionPerformed
        // TODO add your handling code here:
        bilangan+="0";
        kolom.setText(bilangan);
    }//GEN-LAST:event_t0ActionPerformed

    private void tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcActionPerformed
        // TODO add your handling code here:
        bilangan="";
        bilangan1=0.0;
        bilangan2=0.0;
        hasil=0.0;
        kolom.setText("");
    }//GEN-LAST:event_tcActionPerformed

    private void thasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thasilActionPerformed
        // TODO add your handling code here:
        switch (pilih) {
            case 1:
                bilangan2=Double.parseDouble(bilangan);
                hasil=bilangan1+bilangan2;
                bilangan=String.valueOf(hasil);
                kolom.setText(bilangan);
                break;
            case 2:
                bilangan2=Double.parseDouble(bilangan);
                hasil=bilangan1-bilangan2;
                bilangan=String.valueOf(hasil);
                kolom.setText(bilangan);
                break;
            case 3:
                bilangan2=Double.parseDouble(bilangan);
                hasil=bilangan1*bilangan2;
                bilangan=String.valueOf(hasil);
                kolom.setText(bilangan);
                break;
            case 4:
                bilangan2=Double.parseDouble(bilangan);
                hasil=bilangan1/bilangan2;
                bilangan=String.valueOf(hasil);
                kolom.setText(bilangan);
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_thasilActionPerformed

    private void t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_t1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Percobaan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Percobaan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Percobaan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Percobaan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Percobaan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField kolom;
    private javax.swing.JButton t0;
    private javax.swing.JButton t1;
    private javax.swing.JButton t2;
    private javax.swing.JButton t3;
    private javax.swing.JButton t4;
    private javax.swing.JButton t5;
    private javax.swing.JButton t6;
    private javax.swing.JButton t7;
    private javax.swing.JButton t8;
    private javax.swing.JButton t9;
    private javax.swing.JButton tbagi;
    private javax.swing.JButton tc;
    private javax.swing.JButton thasil;
    private javax.swing.JButton tkali;
    private javax.swing.JButton tmin;
    private javax.swing.JButton tplus;
    // End of variables declaration//GEN-END:variables
}
