/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project_UAS;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author User
 */
public class Admin extends javax.swing.JFrame {
    String url;
    File file;
    BufferedReader br;
    BufferedWriter bw;
    DefaultTableModel model;
    
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }
    public void loadData1(){
    url = "src/Project_UAS/user.txt";
        file = new File(url);
        try {
            br = new BufferedReader(new FileReader(file));
            
            String barisPertama = br.readLine();    //ambil baris paling atas pada notepad
            //pisah teks pada barisPertama dengan tanda koma(,)
            //kemudian masukkan ke array
            String[] namaKolom = barisPertama.split(",");
            //ambil model dan atur nama kolom tabel
            model = (DefaultTableModel)tabel.getModel();
            model.setColumnIdentifiers(namaKolom);
            //ambil baris selanjutnya secara keseluruhan
            //dan masukkan ke array
            Object[] dataBaris = br.lines().toArray();
            //lakukan perulangan sebanyak jumlah dataBaris
            for(int i=0;i<dataBaris.length;i++){
                //ambil tiap baris dari dataBaris
                String baris = dataBaris[i].toString();
                //pisah baris dengan tanda / dan masukkan array
                String[] data = baris.split("/");
                //data masukan ke tabel
                model.addRow(data);

            }

        } catch (Exception e) {
        }
    }
    
    public void loadData2(){
    url = "src/Project_UAS/user.txt";
        file = new File(url);
        try {
            br = new BufferedReader(new FileReader(file));
            //ambil baris paling atas pada notepad
            String barisPertama = br.readLine();
            //pisah teks pada barisPertama dengan tanda koma(,)
            //kemudian masukkan ke array
            String[] namaKolom = barisPertama.split(",");
            //ambil model dan atur nama kolom tabel
            model = (DefaultTableModel)tabel.getModel();
            model.setColumnIdentifiers(namaKolom);
            //ambil baris selanjutnya secara keseluruhan
            //dan masukkan ke array
            Object[] dataBaris = br.lines().toArray();
            //lakukan perulangan sebanyak jumlah dataBaris
            for(int i=0;i<dataBaris.length;i++){
                //ambil tiap baris dari dataBaris
                String baris = dataBaris[i].toString();
                //pisah baris dengan tanda / dan masukkan array
                String[] data = baris.split("/");
                //data masukan ke tabel
                model.addRow(data);

            }

        } catch (Exception e) {
        }    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        tambahButton = new javax.swing.JButton();
        cekButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomer Rekening", "Nama", "Saldo"
            }
        ));
        tabel.getTableHeader().setReorderingAllowed(false);
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setResizable(false);
            tabel.getColumnModel().getColumn(1).setResizable(false);
            tabel.getColumnModel().getColumn(2).setResizable(false);
        }

        tambahButton.setText("Tambah");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        cekButton.setText("Cek");
        cekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekButtonActionPerformed(evt);
            }
        });

        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        BG.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BG.setLayer(tambahButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BG.setLayer(cekButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BG.setLayer(hapusButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BG.setLayer(simpanButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(BGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addComponent(cekButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simpanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(tambahButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cekButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(simpanButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hapusButton)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(BG, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        // TODO add your handling code here:
        tambahNasabah tambah = new tambahNasabah();
        tambah.setVisible(true);
        dispose();
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void cekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekButtonActionPerformed
        // TODO add your handling code here:
        //Cek cek = new Cek();
        //cek.setVisible(true);
        
        String url="src//Project_UAS//user.txt";
        File file=new File(url);
        try {
            br = new BufferedReader(new FileReader(file));
            String line1=br.readLine().trim();
            String[] namaKolom=line1.split(",");
            DefaultTableModel model=(DefaultTableModel)tabel.getModel();
            model.setColumnIdentifiers(namaKolom);
            
            Object[] tableLines= br.lines().toArray();
            
            for(int i=0;i<tableLines.length;i++){
                //ambil tiap baris dari dataBaris
                String baris = tableLines[i].toString().trim();
                //pisah baris dengan tanda / dan masukkan array
                String[] dataBaris = baris.split("/");
                //data masukan ke tabel
                model.addRow(dataBaris);

            }
        } catch (IOException e) {
        }
        //dispose();
    }//GEN-LAST:event_cekButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        String msg ="yakin ?";
        JOptionPane.showMessageDialog(rootPane, msg);
        String url="src/Project_UAS/user.txt";
        File file=new File(url);
        try {
            Scanner br=new Scanner(new FileReader(file));
            while (br.hasNextLine()) {
                String data = br.nextLine();
                String[] split=data.split(",");    
            }
            tabel.setValueAt("", tabel.getSelectedRow(), 0);
            tabel.setValueAt("", tabel.getSelectedRow(), 1);
            tabel.setValueAt("", tabel.getSelectedRow(), 2);
            tabel.setValueAt("", tabel.getSelectedRow(), 3);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseClicked

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
        url ="src/Project_UAS/user.txt";
        file = new File(url);
        try {
            bw = new BufferedWriter(new FileWriter(file));
            //Perulangan nama kolom untuk notepad
            for (int i = 0; i < tabel.getColumnCount(); i++) {
                //Pisah kolom dengan koma
                if(i>0){
                    bw.write(",");
                }
                bw.write(tabel.getColumnName(i));    
            }
            bw.newLine();
            //Perulangan data untuk notepad
            for (int i = 0; i < tabel.getRowCount(); i++) {
                //Pisah kolom dengan koma
                for (int j = 0; j < tabel.getColumnCount(); j++){
                    if(j>0)
                        bw.write("/");
                    bw.write(tabel.getValueAt(i, j).toString());
                }
                bw.newLine();
            }
            bw.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_simpanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane BG;
    private javax.swing.JButton cekButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambahButton;
    // End of variables declaration//GEN-END:variables
}
